apply:
  # Description of the service
  description: Remove MQTT discovery storage stands for device
  # Different fields that your service accepts
  fields:
    # Key of the field
    device_id:
      # Description of the field
      description: key to identity every unique device (MAC/name), blank is not supported
      # Example value that can be passed for this field
      example: "'0x00158d000429b869'"
    discovery_topic:
      description: (optional) MQTT discovery topic setting
      example: "homeassistant"